name: Rsync Laravel to EC2 and Notification

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync -y
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 54.224.167.120

      - name: Rsync to EC2
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no" -r --delete-after --quiet ${{ github.workspace }}/ ec2-user@54.224.167.120:/var/www/html/laravel-crud-mysql/
          ssh ec2-user@54.224.167.120 sudo systemctl restart httpd

  slack-notification:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.deploy.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
